# Generated by Django 4.2.23 on 2025-08-27 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('m2_construidos', models.FloatField(default=0)),
                ('m2_totales', models.FloatField(default=0)),
                ('estacionamientos', models.PositiveSmallIntegerField(default=0)),
                ('habitaciones', models.PositiveSmallIntegerField(default=0)),
                ('banos', models.PositiveSmallIntegerField(default=0)),
                ('direccion', models.CharField(max_length=100)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actuallizado', models.DateTimeField(auto_now=True)),
                ('tipo_de_inmueble', models.CharField(choices=[('casa', 'casa'), ('departamento', 'departamento'), ('parcela', 'parcela')], max_length=20)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inmuebles', to='portal.comuna')),
            ],
        ),
    ]
