# Generated by Django 4.2.23 on 2025-08-28 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0002_inmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_de_inmueble',
            field=models.CharField(choices=[('CASA', 'Casa'), ('DEPARTAMENTO', 'Departamento'), ('PARCELA', 'Parcela')], max_length=20),
        ),
    ]
