# Generated by Django 4.2.23 on 2025-08-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_solicitudarriendo_arrendatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiluser',
            name='tipo_usuario',
            field=models.CharField(choices=[('ARRENDATARIO', 'Arrendatario'), ('ARRENDADOR', 'Arrendador')], default='ARRENDATARIO', max_length=13),
        ),
    ]
