# Generated by Django 4.2.23 on 2025-09-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_perfiluser_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(default='sin imagen/', upload_to='inmuebles/'),
        ),
    ]
