# Generated by Django 4.2.23 on 2025-09-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_perfiluser_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(default='sin_imagen/', upload_to='inmuebles/'),
        ),
        migrations.AlterField(
            model_name='perfiluser',
            name='imagen',
            field=models.ImageField(default='default-profile.avif', upload_to='foto_perfil/'),
        ),
    ]
