# Generated by Django 4.2.23 on 2025-09-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_inmueble_imagen_alter_perfiluser_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiluser',
            name='imagen',
            field=models.ImageField(default='fotoperfil.jpg', upload_to='foto_perfil/'),
        ),
    ]
