# Generated by Django 4.2.23 on 2025-09-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_perfiluser_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='actuallizado',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='solicitudarriendo',
            old_name='actuallizado',
            new_name='actualizado',
        ),
        migrations.AlterField(
            model_name='perfiluser',
            name='imagen',
            field=models.ImageField(default='default-profile.avif', upload_to='fotos_perfil/'),
        ),
    ]
